spring.application.name=Hotel Management System

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=ADMIN0107
spring.datasource.password=ADMIN010718
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
