# Entorno CUA (aceptación / pre-producción)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotel_db_cua}
spring.datasource.username=${DB_USERNAME:ADMIN0107}
spring.datasource.password=${DB_PASSWORD:ADMIN010718}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

springdoc.swagger-ui.enabled=true
